seed: 42
dataset:
  train:
    params:
      batch_size: 128
      num_workers: 2
      shuffle: True
    transform:
    - type: ToTensor
  validation:
    params:
      batch_size: 128
      num_workers: 2
      shuffle: True
    transform:
    - type: ToTensor
  test:
    params:
      batch_size: 1
      num_workers: 2
      shuffle: True
    transform:
    - type: ToTensor
general:
  class_hyperparameters:
    loss: 
    - type: NLLLoss
    lr_scheduler: 
    - type: CosineAnnealingLR
      params:
        T_max: 10
        eta_min: 0
    optimizer: 
    - type: Adam
      params:
        lr: 0.001
        weight_decay: 0.0001
    epochs: 5
  grouping_hyperparameters:
    loss: 
    - type: NLLLoss
    grouping_volatility: 1.20
    lr_scheduler: 
    - type: CosineAnnealingLR
      params:
        T_max: 10
        eta_min: 0
    optimizer: 
    - type: Adam
      params:
        lr: 0.01
        weight_decay: 0.0005
    epochs: 5
