seed: 29525
dataset:
  train:
    params:
      batch_size: 500
      num_workers: 64
      shuffle: True
    transform:
    - type: RandAugment
      params:
        num_ops: 2
        magnitude: 8
    - type: ToTensor
    - type: Normalize
      params:
        mean:
        - 0.4914
        - 0.4822
        - 0.4465
        std:
        - 0.2470
        - 0.2435
        - 0.2616
    - type: CutOut
      params:
        n_holes: 2
        length: 4
  validation:
    params:
      batch_size: 500
      num_workers: 64
      shuffle: True
    transform:
    - type: RandAugment
      params:
        num_ops: 2
        magnitude: 8
    - type: ToTensor
    - type: Normalize
      params:
        mean:
        - 0.4914
        - 0.4822
        - 0.4465
        std:
        - 0.2470
        - 0.2435
        - 0.2616
    - type: CutOut
      params:
        n_holes: 1
        length: 4
  test:
    params:
      batch_size: 1
      num_workers: 1
      shuffle: True
    transform:
    - type: ToTensor
    - type: Normalize
      params:
        mean:
        - 0.4914
        - 0.4822
        - 0.4465
        std:
        - 0.2470
        - 0.2435
        - 0.2616
root:
  class_hyperparameters:
    loss: 
    - type: CrossEntropyLoss
    lr_scheduler: 
    - type: StepLR
      params:
        step_size: 20
        gamma: 0.1
    optimizer: 
    - type: Adam
      params:
        lr: 0.01
        weight_decay: 0.0005
    epochs: 90
  grouping_hyperparameters:
    loss: 
    - type: CrossEntropyLoss
    grouping_volatility: 0.88
    lr_scheduler: 
    - type: StepLR
      params:
        step_size: 30
        gamma: 0.1
    optimizer: 
    - type: Adam
      params:
        lr: 0.001
        weight_decay: 0.0005
    epochs: 250
general:
  class_hyperparameters:
    loss: 
    - type: CrossEntropyLoss
    lr_scheduler: 
    - type: StepLR
      params:
        step_size: 30
        gamma: 0.1
    optimizer: 
    - type: Adam
      params:
        lr: 0.01
        weight_decay: 0.0005
    epochs: 200
  grouping_hyperparameters:
    loss: 
    - type: CrossEntropyLoss
    grouping_volatility: 1.02
    lr_scheduler: 
    - type: StepLR
      params:
        step_size: 30
        gamma: 0.1
    optimizer: 
    - type: Adam
      params:
        lr: 0.00023570926966106847
        weight_decay: 0.00021257445443209662
    epochs: 200